---
page-layout: full
format: 
   html: default
   pdf: default
citations-hover: true
link-external-icon: false
link-external-newwindow: true
links-as-notes: true
tbl-colwidths: [5,10,10,45,30]
identifier-prefix: sch
bibliography: references.bib
---

Optional Textbook: @weir2021; Required ebook: @navarroLearningStatisticsJamovi2022

+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
|                     | Week[^1]                   | Date[^2]         | Reading[^3]                                                   | Assignments[^4]                                     |
+=====================+============================+==================+===============================================================+=====================================================+
| {{< bi calendar >}} | [Wk01](/weeks/week-1.qmd)  | `Jan 26`         | Course Introduction (Online via Zoom)                         | Read and study the [Syllabus](course-syllabus.qmd)  |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK02](/weeks/week-2.qmd)  | `Feb 2`          | Introduction to jamovi & Data Collection                      | [`Lab 1`](/labs/lab-1.qmd)                          |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK03](/weeks/week-3.qmd)  | `Feb 9`          | Introduction to Statistics and Measurement                    | Quiz; Major Takeaways                               |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK04](/weeks/week-4.qmd)  | `Feb 16`         | Organizing and Displaying Data\                               | Quizzes; Major Takeaways                            |
|                     |                            |                  | Percentiles                                                   |                                                     |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK05](/weeks/week-5.qmd)  | `Feb 23`         | Measures of Central Tendency\                                 | Quizzes; Major Takeaways; [`Lab 2`](labs/lab-2.qmd) |
|                     |                            |                  | Measures of Variability                                       |                                                     |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK06](/weeks/week-6.qmd)  | `Mar 2`          | Fundamentals of Inferential Statistical\                      | Quiz; Major Takeaways                               |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK07](/weeks/week-7.qmd)  | `Mar 9`          | Correlation and Bivariate Regression                          | Quiz; Major Takeaways                               |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK08](/weeks/week-8.qmd)  | `Mar 16`         | Multiple Correlation and Multiple Regression                  | Quiz; Major Takeaways; [`Lab 3`](labs/lab-3.qmd)    |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | WK09                       | `Mar 23`         | Spring Recess                                                 | Take a rest!                                        |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | WK10                       | `Mar 30`         | `Exam 1`[^5]                                                  | Refer to Canvas                                     |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK11](/weeks/week-11.qmd) | `Apr 6`          | The Student's *t*-test                                        | Quiz; Major Takeaways                               |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK12](/weeks/week-12.qmd) | `Apr 13`         | One-way Analysis of Variance                                  | Quiz; Major Takeaways; `Lab 4`                      |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK13](/weeks/week-13.qmd) | `Apr 20`         | Analysis of Variance With Repeated Measures                   | Quiz; Major Takeaways                               |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK14](/weeks/week-14.qmd) | `Apr 27`         | \                                                             | Quiz; Major Takeaways                               |
|                     |                            |                  | Factorial Analysis of Variance: Between-Between               |                                                     |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK15](/weeks/week-15.qmd) | `May 4`          | \                                                             | Quiz; Major Takeaways; `Lab 5`                      |
|                     |                            |                  | Factorial Analysis of Variance: Between-Within, Within-Within |                                                     |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | [WK16](/weeks/week-16.qmd) | `May 11`         | Analysis of Nonparametric Data                                | Quiz; Major Takeaways                               |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+
| {{< bi calendar >}} | Final's Week               | `May 18`\        | `Exam 2`[^6]                                                  | Refer to Canvas                                     |
|                     |                            | 5:30PM - 7:30PM\ |                                                               |                                                     |
|                     |                            | Redwood Hall 276 |                                                               |                                                     |
+---------------------+----------------------------+------------------+---------------------------------------------------------------+-----------------------------------------------------+

[^1]: The schedule is subject to change.

[^2]: Class Dates: Aug 29, 2022 - Dec 12, 2022

[^3]: Students are expected to read and study the assigned chapters prior to attending each class meeting.

[^4]: Quizzes and Major Takeaways assignments are due `before` class; other assignment are due after class.

[^5]: Covers all previously covered topics.

[^6]: Covers mainly topics presented after Exam 1.
