---
title: "Lab 1 - Data Collection"
editor: visual
reference-location: margin
draft: true
---

## Introduction

This lab in intended to collect data that will be uswed for several purposes throughout the semester.

### Tests

Below, you will find the links to several cognitive tests. Wait for further instructions from your instruction before start taking the tests. This is important because becoming familiar with the tests before other students will likely add noise to the data.

#### 1. Verbal Memory Test

This test measures how many words you can keep in short term memory at once. The number of words you need to remember grows continually, until you can't keep them in your head anymore. Go as long as you can. You have 3 strikes until game over. Your score is how many turns you lasted.

[`Link to take the test`](https://humanbenchmark.com/tests/verbal-memory)

#### 2. Number Memory Test

The average person can only remember 7 digit numbers reliably. Can you do more? You will be presented with a single-digit number and be asked to remember it. The numbers will increase unit you can no longer remember.

[`Link to take the test`](https://humanbenchmark.com/tests/number-memory)

#### 3. Sequence Memory Test

Memorize the sequence of buttons that light up, then press them in order. Every time you finish the pattern, it gets longer. Make a mistake, and the test is over.

[`Link to take the test`](https://humanbenchmark.com/tests/sequence)

#### 4. Chimp Test

This is a test of working memory, made famous by a study that found that chimpanzees consistently outperform humans on this task.

In the study, the chimps consistently outperformed humans, and some chimps were able to remember 9 digits over 90% of the time.

This test is a variant of that concept, that gets increasingly difficult every turn, starting at 4 digits, and adding one every turn. If you pass a level, the number increases. If you fail, you get a strike. Three strikes and the test is over.

[`Link to take the test`](https://humanbenchmark.com/tests/chimp)

#### 5. Typing Test

This is a simple test of typing speed, measuring words per minute, or WPM. The standard measure of WPM is (number of characters / 5) / (time taken). By that measurement, "quick brown fox" is 15 characters, including spaces. The recorded score is WPM \* Accuracy.

[`Link to take the test`](https://humanbenchmark.com/tests/typing)

#### 6. Reaction Time Test

This is a simple tool to measure your reaction time. When the red box turns green, click on the screen as soon as you can. Then, click anywhere to start the new trial.

[`Link to take the test`](https://humanbenchmark.com/tests/reactiontime)

#### 7. Aim Trainer Test

Click the targets as quickly and accurately as you can. This tests reflexes and hand-eye coordination. Once you've clicked 30 targets, your score and average time per target will be displayed.

[`Link to take the test`](https://humanbenchmark.com/tests/aim)

#### 8. Visual Memory Test

Every level, a number of tiles will flash white. Memorize them, and pick them again after the tiles are reset! Levels get progressively more difficult, to challenge your skills. If you miss 3 tiles on a level, you lose one life. You have three lives. Make it as far as you can!

[`Link to take the test`](https://humanbenchmark.com/tests/memory)

## Submission

Submit the scores via [Canvas](canvas.csun.edu).

## Grading

Total points available: 80 points.

| Component | Points[^1] |
|-----------|------------|
| Test 1    | 10         |
| Test 2    | 10         |
| Test 3    | 10         |
| Test 4    | 10         |
| Test 5    | 10         |
| Test 6    | 10         |
| Test 7    | 10         |
| Test 8    | 10         |

[^1]: To earn full points on each test, students must follow the instructions, take the test, and submit the scores and their respective percentiles via Canvas.
